In [2]:
import sys
from pathlib import Path
import pandas as pd

cwd = Path.cwd().resolve()
project_root = cwd.parent if cwd.name == "data-pipeline" else cwd
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.data_loader import *
from src.features import *
from src.paths import (
    PROJECT_ROOT, MARKET_JSONL, PROCESSED_DIR, ORDERBOOK_DIR, FILTERED_TOKEN_IDS, ensure_dirs
)

ensure_dirs()
print("Using project root:", PROJECT_ROOT)

market_jsonl_path = MARKET_JSONL
markets_path = PROCESSED_DIR / "markets.parquet"
tokens_path = PROCESSED_DIR / "tokens.parquet"
filtered_tokens_path = FILTERED_TOKEN_IDS
raw_orderbook_dir = ORDERBOOK_DIR
feat_orderbook_dir = PROCESSED_DIR / "orderbook"

Using project root: C:\Users\Daron\coding\inefficiency-prediction

In [3]:
# TO CREATE MARKETS TABLE
markets_df = read_market_to_df(market_jsonl_path)

# Show the resulting table.
print(markets_df.shape)
markets_df.head()

(356736, 27)

,market_id,condition_id,question,slug,description,start_date,end_date,closed_time,active,closed,...,market_best_bid,market_best_ask,last_trade_price,resolution_source,uma_resolution_status,created_at,updated_at,n_outcomes,outcomes_raw,outcome_prices_raw
0,521502,0x0f8fa51925ce2d46f6767a268e98890258592b193766...,Utah vs. Capitals,nhl-utah-wsh-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:08.57174Z,2025-02-16T17:30:00Z,2025-02-09 22:57:34+00,True,True,...,0.999,1.000,1.0,https://www.nhl.com/,resolved,2025-02-03T07:00:38.152457Z,2025-02-10T21:13:10.419007Z,2,"[""Utah"", ""Capitals""]","[""1"", ""0""]"
1,521503,0x28010eca4446fdd1f3bae2b932fe0071d27dcbab290d...,Lightning vs. Canadiens,nhl-tb-mon-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:18.464733Z,2025-02-16T18:00:00Z,2025-02-09 23:17:30+00,True,True,...,0.999,1.000,1.0,https://www.nhl.com/,resolved,2025-02-03T07:00:52.596765Z,2025-02-10T21:43:12.615134Z,2,"[""Lightning"", ""Canadiens""]","[""1"", ""0""]"
2,521485,0xee068b9b7d89d0a68b1b1940a143e961c5752e294fa9...,Will Elon tweet less than 500 times Jan 31 - F...,will-elon-tweet-less-than-500-times-jan-31-feb-7,This market will resolve according to the numb...,2025-02-03T15:43:11.110902Z,2025-02-07T12:00:00Z,2025-02-05 21:17:55+00,True,True,...,NaN,0.001,1.0,,resolved,2025-02-03T03:32:37.545769Z,2025-02-06T21:05:02.520187Z,2,"[""Yes"", ""No""]","[""0"", ""1""]"
3,521488,0x02c7e0242f53ac51f16c0597d4db9709e1b3bc507faa...,Will Elon tweet 500-524 times Jan 31 - Feb 7?,will-elon-tweet-500-524-times-jan-31-feb-7,This market will resolve according to the numb...,2025-02-03T15:43:35.984934Z,2025-02-07T12:00:00Z,2025-02-06 01:18:23+00,True,True,...,NaN,0.001,1.0,,resolved,2025-02-03T03:32:38.691185Z,2025-02-07T00:09:03.313579Z,2,"[""Yes"", ""No""]","[""0"", ""1""]"
4,521489,0x1b2768ac62dfea779405822eb1fe67691eac684cfba5...,Will Elon tweet 525-549 times Jan 31 - Feb 7?,will-elon-tweet-525-549-times-jan-31-feb-7,This market will resolve according to the numb...,2025-02-03T15:44:00.85876Z,2025-02-07T12:00:00Z,2025-02-06 17:28:37+00,True,True,...,NaN,0.001,1.0,,resolved,2025-02-03T03:32:39.116039Z,2025-02-07T15:31:11.091833Z,2,"[""Yes"", ""No""]","[""0"", ""1""]"

In [4]:
# TO SAVE MARKETS TABLE AS "markets.parquet"
markets_df.to_parquet(markets_path, index=False)

In [5]:
# TO READ MARKETS TABLE FROM "markets.parquet"
markets_df = pd.read_parquet(markets_path)
print(markets_df.shape)
print(markets_df.columns)

(356736, 27)
Index(['market_id', 'condition_id', 'question', 'slug', 'description',
       'start_date', 'end_date', 'closed_time', 'active', 'closed', 'archived',
       'accepting_orders', 'enable_order_book', 'neg_risk', 'fee_decimal',
       'volume', 'volume_clob', 'market_best_bid', 'market_best_ask',
       'last_trade_price', 'resolution_source', 'uma_resolution_status',
       'created_at', 'updated_at', 'n_outcomes', 'outcomes_raw',
       'outcome_prices_raw'],
      dtype='str')

In [6]:
# TO FILTER MARKETS TABLE BY END DATE AND VOLUME, AND GET TOP 70 MARKETS
markets_df = markets_df.dropna(subset=["question", "market_id", "end_date", "closed_time"])
markets_filtered_df = markets_df[markets_df["end_date"] > "2026-01-01"].sort_values("volume", ascending=False).head(70)
relevant_market_ids = set(markets_filtered_df["market_id"].astype(str))
len(relevant_market_ids)

70

In [7]:
# TO CREATE TOKENS TABLE
tokens_df = read_token_to_df(market_jsonl_path)

print(tokens_df.shape)
tokens_df.head()

(713472, 20)

,market_id,token_id,outcome_index,outcome,outcome_price_initial,question,slug,description,start_date,end_date,closed_time,active,closed,archived,accepting_orders,enable_order_book,neg_risk,fee_decimal,volume,volume_clob
0,521502,4278735810733499450033805996998150780100263473...,0,Utah,1.0,Utah vs. Capitals,nhl-utah-wsh-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:08.57174Z,2025-02-16T17:30:00Z,2025-02-09 22:57:34+00,True,True,False,False,True,False,0.02,94610.905573,94610.905573
1,521502,1111661147715280529758155544116704456172196124...,1,Capitals,0.0,Utah vs. Capitals,nhl-utah-wsh-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:08.57174Z,2025-02-16T17:30:00Z,2025-02-09 22:57:34+00,True,True,False,False,True,False,0.02,94610.905573,94610.905573
2,521503,5167092641191119841414124845941123936979062682...,0,Lightning,1.0,Lightning vs. Canadiens,nhl-tb-mon-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:18.464733Z,2025-02-16T18:00:00Z,2025-02-09 23:17:30+00,True,True,False,False,True,False,0.02,134897.501228,134897.501228
3,521503,8574320122684556697660599417444078755289261476...,1,Canadiens,0.0,Lightning vs. Canadiens,nhl-tb-mon-2025-02-09,"In the upcoming NHL game, scheduled for Februa...",2025-02-03T07:03:18.464733Z,2025-02-16T18:00:00Z,2025-02-09 23:17:30+00,True,True,False,False,True,False,0.02,134897.501228,134897.501228
4,521485,1117088797318410927651791754301246752693394101...,0,Yes,0.0,Will Elon tweet less than 500 times Jan 31 - F...,will-elon-tweet-less-than-500-times-jan-31-feb-7,This market will resolve according to the numb...,2025-02-03T15:43:11.110902Z,2025-02-07T12:00:00Z,2025-02-05 21:17:55+00,True,True,False,False,True,True,NaN,190849.597987,190849.597987

In [8]:
# TO SAVE TOKENS TABLE AS "tokens.parquet"
tokens_df.to_parquet(tokens_path, index=False)

In [14]:
# TO READ TOKENS TABLE
tokens_df = pd.read_parquet(tokens_path)

print(tokens_df.shape)
print(tokens_df.columns)

(713472, 20)
Index(['market_id', 'token_id', 'outcome_index', 'outcome',
       'outcome_price_initial', 'question', 'slug', 'description',
       'start_date', 'end_date', 'closed_time', 'active', 'closed', 'archived',
       'accepting_orders', 'enable_order_book', 'neg_risk', 'fee_decimal',
       'volume', 'volume_clob'],
      dtype='str')

In [15]:
# TO FILTER TOKENS TABLE TO ONLY INCLUDE TOKENS FROM THE FILTERED MARKETS
tokens_filtered_df = tokens_df[
    tokens_df["market_id"].astype(str).isin(relevant_market_ids)
].copy()
tokens_filtered_df.shape

(140, 20)

In [12]:
# TO SAVE THE FILTERED TOKEN IDs TO A PARQUET FILE
relevant_token_ids = set(tokens_filtered_df["token_id"].astype(str))

pd.DataFrame({"token_id": sorted(relevant_token_ids)}).to_parquet(filtered_tokens_path, index=False)

In [13]:
await extract_orderbook_from_ids_async(
    token_ids=relevant_token_ids,
    start_date="2025-10-14",
    end_date="2026-03-31",
    output_path=raw_orderbook_dir,
    max_concurrent=8
)

Processing token_id=27110946212212220543885771558729072300747406628273094439631175059267259915499, 1/140
Processing token_id=63864522346594368809423416425052844778517942296857413266450057529414766826445, 2/140
Processing token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952, 3/140
Processing token_id=57969484623906654162647807925252512006821410423354182075797975676232320775740, 4/140
Processing token_id=113930583156121915694796889379494567927783442690238586410669568657607120812138, 5/140
Processing token_id=15002165665234016876486282630507392757515779060349352387653810600083538604826, 6/140
Processing token_id=108381671107274799941073921577360862012191130720671718707997750576881298527847, 7/140
Processing token_id=18491832759883472528052920586615186501076720389035092804420992035191801268891, 8/140
Saved 9,065 rows for token_id=18491832759883472528052920586615186501076720389035092804420992035191801268891 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_18491832759883472528052920586615186501076720389035092804420992035191801268891.parquet
Processing token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984, 9/140
Retry 1/6 token_id=57969484623906654162647807925252512006821410423354182075797975676232320775740 in 2.5s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=57969484623906654162647807925252512006821410423354182075797975676232320775740&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjQ4NDkzMTAwMjksImFzc2V0SWQiOiI1Nzk2OTQ4NDYyMzkwNjY1NDE2MjY0NzgwNzkyNTI1MjUxMjAwNjgyMTQxMDQyMzM1NDE4MjA3NTc5Nzk3NTY3NjIzMjMyMDc3NTc0MCJ9')
Saved 9,913 rows for token_id=113930583156121915694796889379494567927783442690238586410669568657607120812138 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_113930583156121915694796889379494567927783442690238586410669568657607120812138.parquet
Processing token_id=5607394821438033480329831490709557904290234461314111313418562435616991179510, 10/140
Retry 1/6 token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952 in 2.6s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3Njc2MjA0NTgxMDAsImFzc2V0SWQiOiIxNDcwNTAyOTA5MTI5NjE3MTExMDY3NDA4OTM5OTA5MTY1Njk0OTE1NDUyMTA4NjE2MDE2NDAxNzcwODE4NDU2NDI0MTAyMzE0OTk1MiJ9')
Retry 1/6 token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984 in 2.7s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiMjY4NzU3MDQ0MzUxNDQ1NjAxMjMxMjQ4MTQxNjQ5MzExNzE0OTczMzk0NjI3OTk3Mjg0NDk3OTY4MDk4Njg5ODU3MTc1NTEwMzQ5ODQiLCJ0aW1lc3RhbXAiOjE3NjExMDY5NzU0OTd9')
Saved 14,980 rows for token_id=108381671107274799941073921577360862012191130720671718707997750576881298527847 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_108381671107274799941073921577360862012191130720671718707997750576881298527847.parquet
Processing token_id=59971444048982820090749128753331211858318529324980291176754797725178535217659, 11/140
Saved 13,965 rows for token_id=57969484623906654162647807925252512006821410423354182075797975676232320775740 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_57969484623906654162647807925252512006821410423354182075797975676232320775740.parquet
Processing token_id=50578453168420182038439753659781146810201937687957862046851661326350733510943, 12/140
Retry 1/6 token_id=15002165665234016876486282630507392757515779060349352387653810600083538604826 in 2.4s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=15002165665234016876486282630507392757515779060349352387653810600083538604826&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiMTUwMDIxNjU2NjUyMzQwMTY4NzY0ODYyODI2MzA1MDczOTI3NTc1MTU3NzkwNjAzNDkzNTIzODc2NTM4MTA2MDAwODM1Mzg2MDQ4MjYiLCJ0aW1lc3RhbXAiOjE3NjY1NjU2NjUwMTl9')
Retry 1/6 token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952 in 2.7s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiMTQ3MDUwMjkwOTEyOTYxNzExMTA2NzQwODkzOTkwOTE2NTY5NDkxNTQ1MjEwODYxNjAxNjQwMTc3MDgxODQ1NjQyNDEwMjMxNDk5NTIiLCJ0aW1lc3RhbXAiOjE3Njc5NTg4MTc4MTV9')
Saved 17,768 rows for token_id=63864522346594368809423416425052844778517942296857413266450057529414766826445 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_63864522346594368809423416425052844778517942296857413266450057529414766826445.parquet
Processing token_id=98328612241005079298480588888413183448693837922137555607354456149974993923116, 13/140
Saved 19,728 rows for token_id=15002165665234016876486282630507392757515779060349352387653810600083538604826 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_15002165665234016876486282630507392757515779060349352387653810600083538604826.parquet
Processing token_id=113367976184154322931874228808470131715063965970093102075009167307890240904118, 14/140
Retry 1/6 token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952 in 2.0s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjkwNjc0NjI1NjgsImFzc2V0SWQiOiIxNDcwNTAyOTA5MTI5NjE3MTExMDY3NDA4OTM5OTA5MTY1Njk0OTE1NDUyMTA4NjE2MDE2NDAxNzcwODE4NDU2NDI0MTAyMzE0OTk1MiJ9')
Retry 1/6 token_id=59971444048982820090749128753331211858318529324980291176754797725178535217659 in 2.5s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=59971444048982820090749128753331211858318529324980291176754797725178535217659&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3Njg2OTU4NDcwMTIsImFzc2V0SWQiOiI1OTk3MTQ0NDA0ODk4MjgyMDA5MDc0OTEyODc1MzMzMTIxMTg1ODMxODUyOTMyNDk4MDI5MTE3Njc1NDc5NzcyNTE3ODUzNTIxNzY1OSJ9')
Saved 19,319 rows for token_id=50578453168420182038439753659781146810201937687957862046851661326350733510943 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_50578453168420182038439753659781146810201937687957862046851661326350733510943.parquet
Processing token_id=106316402112581431871296425427771662624401052300497693181318308091815990317059, 15/140
Saved 34,930 rows for token_id=27110946212212220543885771558729072300747406628273094439631175059267259915499 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_27110946212212220543885771558729072300747406628273094439631175059267259915499.parquet
Processing token_id=7153839411470716186892401939222845172795686916139860789047682270070337616043, 16/140
Retry 1/6 token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952 in 2.6s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3Njk3MDUzNDQyMTUsImFzc2V0SWQiOiIxNDcwNTAyOTA5MTI5NjE3MTExMDY3NDA4OTM5OTA5MTY1Njk0OTE1NDUyMTA4NjE2MDE2NDAxNzcwODE4NDU2NDI0MTAyMzE0OTk1MiJ9')
Saved 2,548 rows for token_id=106316402112581431871296425427771662624401052300497693181318308091815990317059 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_106316402112581431871296425427771662624401052300497693181318308091815990317059.parquet
Processing token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067, 17/140
Retry 1/6 token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984 in 3.0s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjcyMzY1MDk0MjgsImFzc2V0SWQiOiIyNjg3NTcwNDQzNTE0NDU2MDEyMzEyNDgxNDE2NDkzMTE3MTQ5NzMzOTQ2Mjc5OTcyODQ0OTc5NjgwOTg2ODk4NTcxNzU1MTAzNDk4NCJ9')
Saved 19,885 rows for token_id=59971444048982820090749128753331211858318529324980291176754797725178535217659 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_59971444048982820090749128753331211858318529324980291176754797725178535217659.parquet
Processing token_id=71245395341640282981822050245876486438708685626052577722484604820158902803989, 18/140
Saved 17,039 rows for token_id=113367976184154322931874228808470131715063965970093102075009167307890240904118 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_113367976184154322931874228808470131715063965970093102075009167307890240904118.parquet
Processing token_id=15091760884604171309203489618212539770109612407760305338364320626709285790409, 19/140
Saved 29,260 rows for token_id=14705029091296171110674089399091656949154521086160164017708184564241023149952 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_14705029091296171110674089399091656949154521086160164017708184564241023149952.parquet
Processing token_id=20026306101924418977974295380454723993386366960783931493943507760420571278713, 20/140
Saved 34,925 rows for token_id=26875704435144560123124814164931171497339462799728449796809868985717551034984 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_26875704435144560123124814164931171497339462799728449796809868985717551034984.parquet
Processing token_id=101264163544692975734476704096614714686704159151741493681812911782369649789289, 21/140
Saved 34,428 rows for token_id=5607394821438033480329831490709557904290234461314111313418562435616991179510 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_5607394821438033480329831490709557904290234461314111313418562435616991179510.parquet
Processing token_id=113554675031456886662456333518442351760965732494459471513820718399879139049322, 22/140
Saved 15,895 rows for token_id=7153839411470716186892401939222845172795686916139860789047682270070337616043 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_7153839411470716186892401939222845172795686916139860789047682270070337616043.parquet
Processing token_id=36712164784060438704997454837621402414428053497881693129968518217985319932773, 23/140
Saved 10,428 rows for token_id=101264163544692975734476704096614714686704159151741493681812911782369649789289 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_101264163544692975734476704096614714686704159151741493681812911782369649789289.parquet
Processing token_id=85314966135663911945383444595070372155331802770649765628594996080163644717023, 24/140
Saved 17,767 rows for token_id=71245395341640282981822050245876486438708685626052577722484604820158902803989 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_71245395341640282981822050245876486438708685626052577722484604820158902803989.parquet
Processing token_id=11631590502751337995086584451805403545770829549632613492416833230270784409909, 25/140
Retry 1/6 token_id=15091760884604171309203489618212539770109612407760305338364320626709285790409 in 2.2s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=15091760884604171309203489618212539770109612407760305338364320626709285790409&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiMTUwOTE3NjA4ODQ2MDQxNzEzMDkyMDM0ODk2MTgyMTI1Mzk3NzAxMDk2MTI0MDc3NjAzMDUzMzgzNjQzMjA2MjY3MDkyODU3OTA0MDkiLCJ0aW1lc3RhbXAiOjE3NjgxMzIxNjc3NDZ9')
Saved 20,191 rows for token_id=20026306101924418977974295380454723993386366960783931493943507760420571278713 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_20026306101924418977974295380454723993386366960783931493943507760420571278713.parquet
Processing token_id=53724885359565814757082941140107995442820606989565665748597275515443959778777, 26/140
Saved 36,978 rows for token_id=98328612241005079298480588888413183448693837922137555607354456149974993923116 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_98328612241005079298480588888413183448693837922137555607354456149974993923116.parquet
Processing token_id=80683675731510456248139626451349746383703996709618622135269487159056371210374, 27/140
Retry 1/6 token_id=11631590502751337995086584451805403545770829549632613492416833230270784409909 in 2.5s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=11631590502751337995086584451805403545770829549632613492416833230270784409909&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjgxMjAyMDUwMjgsImFzc2V0SWQiOiIxMTYzMTU5MDUwMjc1MTMzNzk5NTA4NjU4NDQ1MTgwNTQwMzU0NTc3MDgyOTU0OTYzMjYxMzQ5MjQxNjgzMzIzMDI3MDc4NDQwOTkwOSJ9')
Saved 11,929 rows for token_id=85314966135663911945383444595070372155331802770649765628594996080163644717023 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_85314966135663911945383444595070372155331802770649765628594996080163644717023.parquet
Processing token_id=62595435619678438799673612599999067112702849851098967060818869994133628780778, 28/140
Saved 17,772 rows for token_id=36712164784060438704997454837621402414428053497881693129968518217985319932773 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_36712164784060438704997454837621402414428053497881693129968518217985319932773.parquet
Processing token_id=54374622498872887834423251099014698967130619915419293974324817681847068412235, 29/140
Retry 1/6 token_id=54374622498872887834423251099014698967130619915419293974324817681847068412235 in 2.0s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=54374622498872887834423251099014698967130619915419293974324817681847068412235&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiNTQzNzQ2MjI0OTg4NzI4ODc4MzQ0MjMyNTEwOTkwMTQ2OTg5NjcxMzA2MTk5MTU0MTkyOTM5NzQzMjQ4MTc2ODE4NDcwNjg0MTIyMzUiLCJ0aW1lc3RhbXAiOjE3NjE1MjkxNTMyNTJ9')
Retry 1/6 token_id=80683675731510456248139626451349746383703996709618622135269487159056371210374 in 2.8s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=80683675731510456248139626451349746383703996709618622135269487159056371210374&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjkzODU4MzYwMTEsImFzc2V0SWQiOiI4MDY4MzY3NTczMTUxMDQ1NjI0ODEzOTYyNjQ1MTM0OTc0NjM4MzcwMzk5NjcwOTYxODYyMjEzNTI2OTQ4NzE1OTA1NjM3MTIxMDM3NCJ9')
Retry 1/6 token_id=62595435619678438799673612599999067112702849851098967060818869994133628780778 in 2.4s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=62595435619678438799673612599999067112702849851098967060818869994133628780778&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3Njc5MTM2MTc0OTUsImFzc2V0SWQiOiI2MjU5NTQzNTYxOTY3ODQzODc5OTY3MzYxMjU5OTk5OTA2NzExMjcwMjg0OTg1MTA5ODk2NzA2MDgxODg2OTk5NDEzMzYyODc4MDc3OCJ9')
Retry 1/6 token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067 in 2.6s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJhc3NldElkIjoiMTA2NTU3NjA0NzE3NjAyMTEzOTIwNjAwODAxNzQ5OTA0ODc5OTc0NDM0MDMyMTQ1NDg4NDIxODc1MzUwNDAxMTY4MjQ0MjU0NDg2MDY3IiwidGltZXN0YW1wIjoxNzY4OTkwNTg3NjQwfQ%3D%3D')
Saved 19,884 rows for token_id=53724885359565814757082941140107995442820606989565665748597275515443959778777 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_53724885359565814757082941140107995442820606989565665748597275515443959778777.parquet
Processing token_id=113190006934473670021857694313056397492409382226046178751957476405444749578984, 30/140
Saved 16,665 rows for token_id=80683675731510456248139626451349746383703996709618622135269487159056371210374 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_80683675731510456248139626451349746383703996709618622135269487159056371210374.parquet
Processing token_id=52607315900507156846622820770453728082833251091510131025984187712529448877245, 31/140
Saved 12,222 rows for token_id=54374622498872887834423251099014698967130619915419293974324817681847068412235 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_54374622498872887834423251099014698967130619915419293974324817681847068412235.parquet
Processing token_id=8530723144410488573227621851575969317510697903783455903927607049155629901235, 32/140
Retry 1/6 token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067 in 2.6s (502, message='retryable status=502', url='https://api.domeapi.io/v1/polymarket/orderbooks?token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067&start_time=1760400000000&end_time=1774915200000&limit=200&pagination_key=eyJ0aW1lc3RhbXAiOjE3NjkxNTk1MDE1MDEsImFzc2V0SWQiOiIxMDY1NTc2MDQ3MTc2MDIxMTM5MjA2MDA4MDE3NDk5MDQ4Nzk5NzQ0MzQwMzIxNDU0ODg0MjE4NzUzNTA0MDExNjgyNDQyNTQ0ODYwNjcifQ%3D%3D')
Saved 47,182 rows for token_id=15091760884604171309203489618212539770109612407760305338364320626709285790409 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_15091760884604171309203489618212539770109612407760305338364320626709285790409.parquet
Processing token_id=93616795232755165831523474565062299719218096508368365982363091942243564085499, 33/140
Saved 9,963 rows for token_id=8530723144410488573227621851575969317510697903783455903927607049155629901235 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_8530723144410488573227621851575969317510697903783455903927607049155629901235.parquet
Processing token_id=43214578783650551565050661228964951748905800335334196004410896101999020930160, 34/140
Saved 2,962 rows for token_id=93616795232755165831523474565062299719218096508368365982363091942243564085499 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_93616795232755165831523474565062299719218096508368365982363091942243564085499.parquet
Processing token_id=82743364352280803169466972291565729148079169909412980489596558775083675169617, 35/140
Saved 45,978 rows for token_id=106557604717602113920600801749904879974434032145488421875350401168244254486067 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_106557604717602113920600801749904879974434032145488421875350401168244254486067.parquet
Processing token_id=102298659433550248987215228870688081194500704214812846837468302147039715413908, 36/140
Saved 41,340 rows for token_id=113554675031456886662456333518442351760965732494459471513820718399879139049322 to C:\Users\Daron\coding\inefficiency-prediction\data\orderbook\ob_113554675031456886662456333518442351760965732494459471513820718399879139049322.parquet
Processing token_id=58992629418217336791150527105627726520951824426003479091735536985058036672428, 37/140